### ISSUE TITLE
Does not work ! 

### ISSUE THREAD

**Issue by rajeshlousigam** [yuvraj24/react-native-stories-view#14]
Geting Transformer is not a contructor error.

  "dependencies": {
    "@gorhom/bottom-sheet": "3",
    "@react-native-async-storage/async-storage": "^1.15.4",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/cameraroll": "^4.0.4",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/datetimepicker": "^3.4.6",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-picker/picker": "^1.15.0",
    "@react-navigation/material-bottom-tabs": "^5.3.15",
    "@react-navigation/native": "^5.9.4",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "axios": "^0.21.1",
    "lottie-ios": "^3.2.0",
    "lottie-react-native": "^3.5.0",
    "moment": "^2.29.1",
    "patch-package": "^6.4.7",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-animated-pagination-dots": "^0.1.72",
    "react-native-camera": "^3.43.6",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-image-crop-picker": "^0.36.0",
    "react-native-immersive-mode": "^2.0.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-masonry-list": "^2.16.1",
    "react-native-pager-view": "^5.1.5",
    "react-native-paper": "^4.7.2",
    "react-native-popup-menu": "^0.15.10",
    "react-native-reanimated": "^2.1.0",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.1.0",
    "react-native-stories-view": "^1.0.7",
    "react-native-svg": "^12.1.1-0",
    "react-native-tab-view": "^2.16.1",
    "react-native-text-gradient": "^0.1.7",
    "react-native-thumbnail": "^1.1.3",
    "react-native-vector-icons": "^8.1.0",
    "react-native-video": "^5.1.1",
    "react-native-video-processing": "^2.0.0",
    "react-native-virtual-keyboard": "^1.1.0",
    "react-redux": "^7.2.4",
    "react-spring": "^9.1.0",
    "redux": "^4.1.0",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.23",
    "@types/react": "^17.0.5",
    "@types/react-native": "^0.64.5",
    "@types/react-test-renderer": "^17.0.1",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1",
    "typescript": "^4.2.4"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by SaeedGujjar** [comment]
same error

**Comment by CMLCNL** [comment]
same error

**Comment by yuvraj24** [comment]
Have published a new version of [1.0.9](https://www.npmjs.com/package/react-native-stories-view)......update to the latest version now !!!
