### ISSUE TITLE
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by saad9624-tribalScale** [yuvraj24/react-native-stories-view#24]
I am getting this error.
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

**Comment by Hewr-Srood** [comment]
@saad9624-tribalScale I got the same error any solution?

**Comment by AtaMuhiuldin** [comment]
Getting the same issue as well!

**Comment by yuvraj24** [comment]
The issue seems to be resolved thanks to the awesome work done by @vkoktashev. Have published a new version of [1.0.9](https://www.npmjs.com/package/react-native-stories-view)......update to the latest version now !!!
