### ISSUE TITLE
Module RCTLog is not a registered callable module

### ISSUE THREAD

**Issue by andreypaul** [yuvraj24/react-native-stories-view#3]
Does not work:

![Simulator Screen Shot - iPhone 7 - 2020-07-20 at 12 35 32](https://user-images.githubusercontent.com/17850013/87923027-8475df80-ca85-11ea-9713-06b560d65d80.png)

**Comment by ilya-raevskiy** [comment]
I have the same

**Comment by emrecandurmus** [comment]
I have the same issue.

**Comment by khoand0407** [comment]
same issue, this library can't use, close this project, please

**Comment by Saad9624** [comment]
same issue

**Comment by frxzn** [comment]
same

**Comment by hackyxicor** [comment]
same issue

**Comment by dbradham** [comment]
Same as above

**Comment by yuvraj24** [comment]
Seems like I am not able to replicate this issue at my end.
Can anyone share a demo code here with this same exact scenario, that would help !!!

**Comment by raghvendra007** [comment]
when you install npm ,made a build and try to run it it will give error of HMRClient is not a registered callable module

**Comment by Billmike** [comment]
@yuvraj24 This is still an issue. The Library is unusable on Android. I copied the example code in the `example/App.js` file and tried running it after installing the package. It results in the error `HMRClient is not a registered callable module`.

**Comment by yuvraj24** [comment]
@Billmike it would be helpful, if you can share that demo source code with me for investigation of this issue.

**Comment by yuvraj24** [comment]
Have published a new version of [1.0.9](https://www.npmjs.com/package/react-native-stories-view)......update to the latest version now.
