### ISSUE TITLE
License

### ISSUE THREAD

**Issue by marek-baranowski** [yuvraj24/react-native-stories-view#31]
Hello,

As this appears to be an open source project, the missing license info makes it basically not possible to use by others, as stated here https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

>However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

Could you please clarify this issue? And if it's intended for OSS, then could you kindly include the relevant file or update package.json with the "license" entry?

All the best and thank you for your great work!

**Comment by yuvraj24** [comment]
Added License as requested by @marek-baranowski...
https://github.com/yuvraj24/react-native-stories-view/blob/master/LICENSE
