### ISSUE TITLE
Module RCTDeviceEventEmitter is not a registered callable module

### ISSUE THREAD

**Issue by lalitkumarrock** [yuvraj24/react-native-stories-view#9]
Hii ,

I'm using this library with version 1.0.7 and i'm facing this issue 

Module RCTDeviceEventEmitter is not a registered callable module

**Comment by Vahabov** [comment]
@lalitkumarrock How did you solve the problem?

**Comment by yuvraj24** [comment]
Have published a new version of [1.0.9](https://www.npmjs.com/package/react-native-stories-view)......update to the latest version now !!!

**Comment by Vahabov** [comment]
Hi. Thank you for feedbaHi. Thank you for your feedback. Have any examples?

**Comment by Vahabov** [comment]
Hi. Thank you for your feedback. Have any examples?
